const Items = [
  {
    id: 1,
    mainImage: "/Ecom2.png",
    img: ["/Ecom1.png", "/Ecom2.png", "/Ecom3.png", "/Ecom4.png", "/Ecom5.png"],
    features: [
      "Home",
      "About",

      "Contact",
      "Product Add",

      "A user can order through the Admin for Website services, Mobile Applications, Branding & Creative Content, as well as Internet Marketing & Advertising.",
      "Responsive Design",
      "404 Page and many more.",
    ],
    technologies: [
      "React",
      "TailwindCSS",
      "React Roudter",
      "Redux",
      "React icons",
      "Email JS",
      "Framer Motion",
      "FakeProduct Api",
    ],
    title: "Sumit Ecommerce",
    description:
      "Sumit Ecommerce is a modern and user-friendly online shopping platform designed to provide a seamless shopping experience. It features a wide range of products, secure payment options, and an intuitive interface for browsing and purchasing. Whether you're looking for the latest trends or everyday essentials, Sumit Ecommerce ensures a fast, reliable, and enjoyable shopping journey. With advanced search filters and personalized recommendations, it's your one-stop destination for all your shopping needs!",
    category: "business",
    liveLink: "https://change-ecom.vercel.app/",
    codeLink: "https://github.com/Sumit6569/Change-Ecom",
  },
  {
    id: 2,
    mainImage: "/Obeys1.png",
    img: [
      "/Obeys1.png",
      "/Obeys2.png",
      "/obyes3.png",
      "/obeys4.png",
      "/obeys5.png",
      "/obeys6.png",
    ],
    features: [
      "Static Site",
      "Smoothe Scrolling",
      "Advanced Colors",
      "Text Animation",
    ],
    technologies: [
      "Html",
      "Css",
      "JavaScript",
      "Scroll Trigger",
      "Loco Motive",
      "GSAP Animation",
    ],
    title: "Obeys Agency",
    description: "Creating The Clone Of Obeys Agency",
    category: "personal",
    liveLink: "https://sumit6569.github.io/ObysAgency/",
    codeLink: "https://github.com/Sumit6569/ObysAgency",
  },
  {
    id: 3,
    mainImage: "/Java1.png",
    img: ["/Java1.png", "/java2.png", "/java3.png"],
    features: [
      "Inset Noder",
      "Insertion of Node Follow AVL TREE",
      "Deletaion of Node",
      "Search of Node",
      "Traversal of AVL Tree",
    ],
    technologies: [
      "Java Swing",
      "AWT",
      "ConcurrentLinkedQueue",
      "Java Collections (List, ArrayList)",
      "SwingUtilities",
      "Timers",
    ],
    title: "Avl Tree Visualizer",
    description:
      "A java Project that Show the Avl Tree Visualizer useing Avl Tree Algorithms ",
    category: "personal",
    liveLink: "/",
    codeLink: "https://github.com/Sumit6569/JavaAvlTreeVisulaizer",
  },
  {
    id: 4,
    mainImage: "/refocous1.png",
    img: ["/refocous1.png", "/refocous2.png", "/refocous3.png"],
    features: ["Advanced Desing", "HeroSectioni"],
    technologies: [
      "React",
      "React Hooks",
      "React Icons",
      "React Vite",
      "Redux",

      "Tailwind CSS",
      "Apexcharts",
      "Localforage",
    ],
    title: "Refocous ",
    description: "Clone of Refocous That is Awarder Web Page ",
    category: "business",
    liveLink: "https://refocous.vercel.app/",
    codeLink: "https://github.com/Sumit6569/Refocous",
  },
  {
    id: 5,
    mainImage: "/Music1.png",
    img: ["/Music1.png", "/Music2.png"],
    features: ["Advanced Desing", "HeroSectioni"],
    technologies: [
      "Html",
      "Css",
      "javascript",
      "Icons",
      "React Vite",
      "Tailwind CSS",
    ],
    title: "My Music ",
    description: "Creating first Project for Useing Html , Css , JavaScript",
    category: "business",
    liveLink:
      "https://music-eawnqlu1q-sumit-kumars-projects-f4b706b1.vercel.app/",
    codeLink: "https://github.com/Sumit6569/MusicApp",
  },
];

export default Items;
